
provisioner:
  type: sagemaker_pytorch
  job_name_base: "squad-bert-ft"
  inputs_paths: # multiple key-pairs allowed here, see entry_point file how to use them
    train: "s3://applied-ml/block_movement_pruning/training-data/"
  # instance_type: "ml.p2.xlarge"
  instance_type: "ml.g4dn.xlarge" # cheap gpu for testing
  #instance_type: ml.c5.xlarge
  dependencies: ["block_movement_pruning", "mlops", "entrypoints"]
  entry_point: entrypoints/squad_bert_ft_entry_point.py #
  framework_version: "1.9.1"
  py_version: py38
  use_spot_instances: False
  #Alternatively, instead of a python and framework version, use a custom docker image:
  #docker_image_uri: "679792626450.dkr.ecr.us-east-1.amazonaws.com/sagemaker-tf2.4.0-py3.7.4-gpu:latest"
  # Tags for cost tracking and more
  allow_dirty_git: True
  tags:
    expcode: "mlops-test" # TODO: change this. Get code from Ravish
    purpose: "development"
    entity: "mlops"

# out_dir: &out_dir
#   /opt/ml/checkpoints/

# trackers:
#   - type: wandb
#     run_id_dir: "/opt/ml/checkpoints/"
#     project_name: test-mlops-examples
#     team: applied-machine-learning
#     is_sweep: False
#     tags:
#       1: baseline
